name: Submit Python Package

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v4
              with:
                python-version: "3.9"

            - name: Install dependencies
              run: |
                python -m pip3 install --upgrade pip3
                python -m pip3 install Pillow numpy filetype setuptools wheel twine
          
            - name: Build binary wheel and a source tarball
              run: python setup.py sdist bdist_wheel

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: ${{ secrets.PYPI_API_TOKEN }}
                repository_url: https://upload.pypi.org/legacy/
