name: Release package

on:
  workflow_dispatch:

jobs:
  releasepypi:
    name: Release to PyPI
    runs-on: macos-latest
    environment:
      name: release
      permissions:
        packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust this based on your project's requirements

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

      - name: Install build tooling
        run: |
          python -m pip install --upgrade build

      - name: Build distributions
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
