name: Publish Python distributions to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build distribution package
        run: |
          python setup.py sdist bdist_wheel

      - name: Run tests
        run: |
          pip install -r requirements.txt  # Install package dependencies for testing
          pytest  # Run tests using pytest

      - name: Publish distribution to PyPI
        if: matrix.python-version == '3.10'  # Publish only once (e.g., on Python 3.10)
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
