name: Release package

on:
  workflow_dispatch:

jobs:
  releasepypi:
    name: Release to PyPI
    runs-on: "macos-latest"
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Run tests (one last time before release)
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run pip3 install --editable .
          pipenv run pytest tests/

      - name: Install build tooling
        run: python3 -m pip install --upgrade build

      - name: Build distributions
        run: python3 -m build

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # To test: repository_url: https://test.pypi.org/legacy/
