name: Publish Python distributions to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish Python distribution
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build and packaging tools
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build distribution package
        run: |
          python -m build

      - name: Publish distribution to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
