name: Publish Python distributions to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build distribution package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

